// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ukeW6Q4V5F5eI47t4s9-S3jXq-CJtTM',
    appId: '1:948893321768:android:d490a4762780c619c5831d',
    messagingSenderId: '948893321768',
    projectId: 'eventapp-1cc7e',
    storageBucket: 'eventapp-1cc7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuw7505LNvcsQ_Hx2ZHQN6wKLUYLufrpE',
    appId: '1:948893321768:ios:7b9c3a6566b321d7c5831d',
    messagingSenderId: '948893321768',
    projectId: 'eventapp-1cc7e',
    storageBucket: 'eventapp-1cc7e.appspot.com',
    androidClientId: '948893321768-gn5jq72imgh0iqf9qvisgrd3njsd7rti.apps.googleusercontent.com',
    iosClientId: '948893321768-g40tsahdmhr0pqk30k605mugmnl7ag7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.ems',
  );
}
